### ISSUE TITLE
Import SYS in main.py

### ISSUE THREAD

**Issue by citizenstaar** [docker-forensics-toolkit/toolkit#2]
![image](https://user-images.githubusercontent.com/17726673/105559596-9740c980-5cdf-11eb-9712-1dd0988a593b.png)

**Comment by citizenstaar** [comment]
Please let me know if you need anything else.  Thank you for publishing this tool.

**Comment by johanneswseitz** [comment]
Should be fixed now. Try again.

Cheers

**Comment by citizenstaar** [comment]
Danke!  :)
